sudo: false

language: erlang
otp_release:
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R15B03
  - R15B02
  - R15B01
  - R14B04
  - R14B03

addons:
  apt:
    packages:
      - autotools-dev
      - libpam0g-dev
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-font-utils
      - texlive-extra-utils
      - ghostscript

install:
  - autoreconf -vfi

before_script:
  - ./configure

script:
  - make distcheck -j4 V=1

after_script:
  - rebar get-deps compile
